# Generated by Django 5.0.6 on 2024-07-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_userprofile_email_alter_userprofile_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tag',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
