# Generated by Django 5.0.6 on 2024-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promts',
            fields=[
                ('post_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('promtext', models.TextField()),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('user_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
