# Generated by Django 5.0.6 on 2024-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_userprofile_email_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tag',
            field=models.CharField(default='default_tag', max_length=20),
        ),
    ]
